### ISSUE TITLE
W

### ISSUE THREAD

**Issue by UIKeep01** [serversigns/ServerSigns#63]
W

**Comment by EpiCanard** [comment]
What do you mean by different directory ? For example create a new map with multiverse ?
Signs are not created inside world directory but inside plugins directory (plugins/ServerSigns/signs)

Maybe there an error inside the log ? If the sign doesn't work it was moved to the directory invalid and disabled.

I already have signs on multiple worlds on my server and it works so maybe the error is somewhere else. (Invalid sign for example)

**Comment by UIKeep01** [comment]
![c1](https://github.com/serversigns/ServerSigns/assets/123191146/0de03bb8-7ffb-434c-a327-287a38ecf16d)
![c2](https://github.com/serversigns/ServerSigns/assets/123191146/c73e0271-55d1-4476-a263-6e86e5f77264)

**Comment by EpiCanard** [comment]
There's not a single use of the word worlds in all the project.
Maybe someone with access to you server created this folder.

Try to move the file Jumpcraft - Parkour in the folder plugins/ServerSigns/signs

**Comment by UIKeep01** [comment]
No, it's how I'm storing my world.
![d](https://github.com/serversigns/ServerSigns/assets/123191146/925221aa-5431-40bd-8373-554df1663b38)
![d2](https://github.com/serversigns/ServerSigns/assets/123191146/bb86c8fc-09f9-41cd-8af8-6b56631ce8ff)
You can put worlds in different directories, the way I imported the world was /mv import "worlds/JumpCraft - Parkour"
I assume that the plugin does not know how to work with worlds in different directories properly.

**Comment by UIKeep01** [comment]
> No, it's how I'm storing my world. ![d](https://user-images.githubusercontent.com/123191146/265837182-925221aa-5431-40bd-8373-554df1663b38.png) ![d2](https://user-images.githubusercontent.com/123191146/265837193-bb86c8fc-09f9-41cd-8af8-6b56631ce8ff.png) You can put worlds in different directories, the way I imported the world was /mv import "worlds/JumpCraft - Parkour" I assume that the plugin does not know how to work with worlds in different directories properly.

**Comment by UIKeep01** [comment]
No, it's how I'm storing my world. d d2 You can put worlds in different directories, the way I imported the world was /mv import "worlds/JumpCraft - Parkour"
I assume that the plugin does not know how to work with worlds in different directories properly.
![d](https://github.com/serversigns/ServerSigns/assets/123191146/eb72e184-91b7-4582-94c7-29e163857978
![d2](https://github.com/serversigns/ServerSigns/assets/123191146/8afc6281-b268-4ccf-847c-f6b340230b90)
)

**Comment by UIKeep01** [comment]
> There's not a single use of the word worlds in all the project. Maybe someone with access to you server created this folder.
> 
> Try to move the file Jumpcraft - Parkour in the folder plugins/ServerSigns/signs

No, it's how I'm storing my world. d d2 You can put worlds in different directories, the way I imported the world was /mv import "worlds/JumpCraft - Parkour" I assume that the plugin does not know ho
![d2](https://github.com/serversigns/ServerSigns/assets/123191146/2393c325-c2c5-4112-8b65-9c54d60782fd)
w to work with worlds in different directories properly.
![d](https://github.com/serversigns/ServerSigns/assets/123191146/11d95baf-b7e6-448c-97ed-f3a4910de853)

**Comment by EpiCanard** [comment]
I see, I will try to reproduce the bug on my side

**Comment by EpiCanard** [comment]
I can reproduce

**Comment by EpiCanard** [comment]
The fix is available here https://github.com/serversigns/ServerSigns/releases/tag/v4.9.1

**Comment by UIKeep01** [comment]
> The fix is available here https://github.com/serversigns/ServerSigns/releases/tag/v4.9.1

I still get the same result - it works fine first, but when I restart the server or do /svs reload, it no longer works.

**Comment by EpiCanard** [comment]
It doesn't move the signs created in previous version. Recreate your sign and it will work. If the sign is really complex you can move it in signs folder

**Comment by EpiCanard** [comment]
Can you do an /mv list ?

**Comment by UIKeep01** [comment]
> Can you do an /mv list ?
https://vimeo.com/862190438

**Comment by EpiCanard** [comment]
Try this one https://github.com/serversigns/ServerSigns/releases/tag/v4.9.1
(it's the same version number but the content change, you can download this version)

**Comment by UIKeep01** [comment]
Ok, it works now, thanks.
